"""Import existing exports (tdesktop HTML or previous tg-export)."""

from __future__ import annotations

import logging
import re
from pathlib import Path

from tg_export.config import ImportExistingEntry

logger = logging.getLogger(__name__)

# Media subdirs in tdesktop HTML export. A tuple, not a set: the order of the
# alternatives below is the order of iteration, and a set orders its strings by
# hash -- which PYTHONHASHSEED randomises per process. The pattern would then
# differ from run to run, so any failure that depended on it would reproduce
# only sometimes.
_TDESKTOP_MEDIA_SUBDIRS = (
    "photos",
    "files",
    "video_files",
    "voice_messages",
    "video_messages",
    "stickers",
    "gifs",
)

# Regex patterns for tdesktop HTML parsing.
#
# Why not html.parser: the index needs exactly two things from a page --
# the id of a message and the href of its media file -- and the pages are
# machine-generated by one program, so their markup does not vary. A parser
# would build a tree of every message of a chat (files of tens of megabytes)
# to reach the same two attributes, and the scan below runs line by line
# without holding the document in memory. If tdesktop ever changes the shape
# of its output, this is the place that has to change with it.
# How many lines of the tdesktop page are read looking for the chat name: it
# sits in the header, and reading the whole page -- megabytes of messages --
# to find it would cost the entire import.
_CHAT_NAME_HEADER_LINES = 50

# Upper bound on the number of `messagesN.html` pages of one chat. The loop
# stops at the first missing page; the bound only keeps a mistake from turning
# into an endless walk.
_MAX_TDESKTOP_PAGES = 10000

_MSG_ID_RE = re.compile(r'id="message(\d+)"')
_HREF_RE = re.compile(r'href="[^"]*?/chats/[^"]*?/(' + "|".join(_TDESKTOP_MEDIA_SUBDIRS) + r')/([^"]+)"')


class TdesktopIndex:
    """Lazy per-chat index of tdesktop HTML export.

    Pre-scans chat directories to build chat_name -> chat_dir mapping.
    Per-chat media index (msg_id -> file_path) is built on demand.
    """

    def __init__(self, export_path: Path):
        self.export_path = export_path
        self._chat_map: dict[str, Path] | None = None  # chat_name -> chat_dir
        self._current_chat_dir: Path | None = None
        self._current_index: dict[int, list[Path]] | None = None  # msg_id -> [file_paths]

    def _ensure_chat_map(self):
        """Build chat_name -> chat_dir mapping from tdesktop export."""
        if self._chat_map is not None:
            return

        self._chat_map = {}
        chats_dir = self.export_path / "chats"
        if not chats_dir.is_dir():
            logger.warning("tdesktop export has no chats/ directory: %s", self.export_path)
            return

        for chat_dir in sorted(chats_dir.iterdir()):
            if not chat_dir.is_dir() or not chat_dir.name.startswith("chat_"):
                continue
            msg_html = chat_dir / "messages.html"
            if not msg_html.exists():
                continue
            name = _extract_chat_name(msg_html)
            if name:
                self._chat_map[name] = chat_dir
                logger.debug("tdesktop chat: %s -> %s", name, chat_dir.name)

        logger.info("tdesktop index: %d chats in %s", len(self._chat_map), self.export_path)

    def find_chat_dir(self, chat_name: str) -> Path | None:
        """Find tdesktop chat directory by chat name."""
        self._ensure_chat_map()
        assert self._chat_map is not None
        return self._chat_map.get(chat_name)

    def load_chat_index(self, chat_name: str) -> bool:
        """Build msg_id -> file_paths index for a specific chat.

        Returns True if chat was found and indexed.
        """
        chat_dir = self.find_chat_dir(chat_name)
        if chat_dir is None:
            self._current_chat_dir = None
            self._current_index = None
            return False

        if self._current_chat_dir == chat_dir:
            return True  # already loaded

        self._current_chat_dir = chat_dir
        self._current_index = _parse_chat_media(chat_dir)
        logger.info("tdesktop index for '%s': %d messages with media", chat_name, len(self._current_index))
        return True

    def unload_chat_index(self):
        """Free memory for current chat index."""
        self._current_chat_dir = None
        self._current_index = None

    def find_file(self, msg_id: int) -> Path | None:
        """Find file path for a message in the current chat index.

        Returns absolute path to the file, or None.
        Only returns the first (primary) file for a message.
        """
        if self._current_index is None:
            return None
        files = self._current_index.get(msg_id)
        if not files:
            return None
        for f in files:
            if f.exists():
                return f
        return None


def _extract_chat_name(msg_html: Path) -> str | None:
    """Extract chat name from tdesktop messages.html header.

    Reads only the first `_CHAT_NAME_HEADER_LINES` lines: the name is in the header.
    """
    try:
        with open(msg_html, encoding="utf-8") as f:
            for i, line in enumerate(f):
                if i > _CHAT_NAME_HEADER_LINES:
                    break
                if "text bold" in line:
                    # Next line contains the chat name
                    name_line = next(f, "").strip()
                    if name_line:
                        return name_line
    except OSError as e:
        # Without this line the chat is simply missing from the index and the
        # import silently does nothing for it.
        logger.debug("tdesktop chat name unreadable in %s: %s", msg_html, e)
    return None


def _parse_chat_media(chat_dir: Path) -> dict[int, list[Path]]:
    """Parse all messages*.html in a chat dir to build msg_id -> [file_paths] index.

    Scans for id="messageNNN" and href=".../(photos|files|...)/filename" pairs.
    Files are resolved relative to the export root (chat_dir/../../).
    """
    index: dict[int, list[Path]] = {}

    # Collect all message HTML files in order
    html_files = [chat_dir / "messages.html"]
    for i in range(2, _MAX_TDESKTOP_PAGES):
        f = chat_dir / f"messages{i}.html"
        if not f.exists():
            break
        html_files.append(f)

    chat_dir_resolved = chat_dir.resolve()
    for html_file in html_files:
        current_msg_id = None
        try:
            with open(html_file, encoding="utf-8") as f:
                for line in f:
                    m = _MSG_ID_RE.search(line)
                    if m:
                        current_msg_id = int(m.group(1))

                    if current_msg_id is not None:
                        m = _HREF_RE.search(line)
                        if m:
                            subdir = m.group(1)
                            filename = m.group(2)
                            # Skip thumbnails
                            if "_thumb" in filename:
                                continue
                            file_path = chat_dir / subdir / filename
                            # Why: tdesktop HTML is external input; reject paths
                            # that resolve outside chat_dir (../, symlinks).
                            try:
                                resolved = file_path.resolve()
                            except OSError:
                                continue
                            if not resolved.is_relative_to(chat_dir_resolved):
                                logger.warning(
                                    "tdesktop import: skipping path outside chat dir: %s",
                                    file_path,
                                )
                                continue
                            if current_msg_id not in index:
                                index[current_msg_id] = []
                            index[current_msg_id].append(file_path)
        except OSError as e:
            logger.warning("Error reading %s: %s", html_file, e)

    if html_files and not index:
        logger.info("tdesktop: no media references found in %s", chat_dir)
    return index


def build_tdesktop_indexes(import_entries: list[ImportExistingEntry]) -> list[TdesktopIndex]:
    """Build TdesktopIndex instances from config import_existing entries."""
    indexes = []
    for entry in import_entries:
        if entry.type != "tdesktop":
            continue
        path = Path(entry.path).expanduser()
        if not path.is_dir():
            logger.warning("tdesktop export not found: %s", path)
            continue
        indexes.append(TdesktopIndex(path))
    return indexes
